create table if not exists public.items (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid(),
  owner_name text not null,
  owner_email text not null,
  name text not null,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  status text not null default 'available' check (status in ('available', 'unavailable')),
  photo_url text not null default '',
  photo_path text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists items_owner_id_idx on public.items (owner_id);
create index if not exists items_created_at_idx on public.items (created_at desc);

alter table public.items enable row level security;

drop policy if exists "items_select_all" on public.items;
drop policy if exists "items_insert_own" on public.items;
drop policy if exists "items_update_own" on public.items;
drop policy if exists "items_delete_own" on public.items;

create policy "items_select_all"
on public.items
for select
to public
using (true);

create policy "items_insert_own"
on public.items
for insert
to authenticated
with check (owner_id = auth.uid());

create policy "items_update_own"
on public.items
for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

create policy "items_delete_own"
on public.items
for delete
to authenticated
using (owner_id = auth.uid());
